### ISSUE TITLE
Instructions for installation

### ISSUE THREAD

**Issue by luisvd** [humboldtux/startbootstrap-clean-blog#1]
I downloaded your theme, however you are missing the instructions to install it from the scratch. There is instructions for your demo. However it needs instructions for a vanilla new site in this project using hugo.

Thank you for such an amazing work

**Comment by humboldtux** [comment]
What kind of instructions are you exactly looking for?

**Comment by luisvd** [comment]
Inside of the Readme of this project, it must include the same instructions as the demo without the git push or git related publish, with a reference to the demo site just like the other themes. This is to make the process of installing the theme easier and faster.

Also the configuration in the demo site readme is missing the 
[params]
 Description = "Your site description"

Hugo will cut the index.html and stop the compile. Since it is expecting {{ title .Site.Params.Description }}

**Comment by humboldtux** [comment]
I've updated the README and made the .Site.Params.Description optional.

I'm closing this issue, not that i think the README is perfect.

You are welcome to open another one for any other issue with the theme and its instructions.
