### ISSUE TITLE
404 Page - Index Link refers to self

### ISSUE THREAD

**Issue by danward79** [humboldtux/startbootstrap-clean-blog#20]
When the 404 page is served the link "Index" actually refers back to the URL of the 404 page.

The template uses .URL, which according to the documents is:

> .URL The relative URL for this page.

The link should be changed from:
`<p class="post-meta"><a href="{{ .URL }}">Index</a> `
to
`<p class="post-meta"><a href="{{ .Site.BaseURL }}">Index</a>`

Provided there is no other intention? I'll submit a fix.

**Comment by humboldtux** [comment]
I think it's a bug, but i can't check this for now. You are more than welcome to submit a PR @danward79 .
