### ISSUE TITLE
Error when generating example site

### ISSUE THREAD

**Issue by spf13** [humboldtux/startbootstrap-clean-blog#3]
==== PROCESSING  startbootstrap-clean-blog  ======
Building site for theme startbootstrap-clean-blog using config config-startbootstrap-clean-blog.toml
ERROR: 2016/01/06 17:28:39 template.go:127: Unable to render [page/archive.html _default/archive.html theme/page/archive.html theme/_default/archive.html]
ERROR: 2016/01/06 17:28:39 template.go:128: Expecting to find a template in either the theme/layouts or /layouts in one of the following relative locations [page/archive.html _default/archive.html theme/page/archive.html theme/_default/archive.html]

**Comment by humboldtux** [comment]
@spf13 I need to update the theme.

I will look at this, this week end.

Thank you.

**Comment by gionn** [comment]
This can be closed @humboldtux, just running master with latest hugo and working fine.

**Comment by humboldtux** [comment]
Thank you Giovanni for your feedback.
