### ISSUE TITLE
Could you either provide an example site or make .Params.DateForm optional?

### ISSUE THREAD

**Issue by yihui** [humboldtux/startbootstrap-clean-blog#30]
Without a working `exampleSite/`, it can be confusing to beginners, who may not really understand what the error message means: https://github.com/rstudio/blogdown/issues/229

> `ERROR 2017/11/10 14:28:55 Error while rendering "page": template: theme/post/single.html:15:20: executing "theme/post/single.html" at <partial "meta.html" ...>: error calling partial: template: theme/partials/meta.html:4:74: executing "theme/partials/meta.html" at <.Site.Params.datefor...>: invalid value; expected string`

**Comment by asimumba** [comment]
@humboldtux It would be nice if you could provide the `exampleSite` for this great theme. Thanks in advance.

**Comment by humboldtux** [comment]
What is an `exampleSite`?

**Comment by yihui** [comment]
It is, ummm, an example site... https://github.com/gohugoio/hugoThemes#adding-a-theme-to-the-list

Many themes ship example sites in their `exampleSite` folders, e.g., https://github.com/yihui/hugo-xmin/tree/master/exampleSite

**Comment by asimumba** [comment]
@humboldtux in terms of building the site with hugo commands directly on the command line, everything works great. But if one tries to implement the theme via @yihui package, [**blogdown**](https://github.com/rstudio/blogdown/issues/193), the site builds but only with bare bones without  `CSS` customization. This is equally the case if you preview the public folder on [**netlify**](https://www.netlify.com/).

**Comment by yihui** [comment]
As I said in the title of this issue, you should consider making `.Params.DateForm` optional (e.g. use [the `default` function](https://gohugo.io/functions/default/) to provide a default date format), otherwise this theme does not work out of the box (users must add this parameter in `config.toml`):

https://github.com/humboldtux/startbootstrap-clean-blog/blob/11318ff5dd8e3104682f7065c24865e0b4a1c80b/layouts/post/archive.html#L2

**Comment by humboldtux** [comment]
See #34 and #35.

**Comment by paskal** [comment]
#37 is about the very same thing.
