### ISSUE TITLE
Populating description and author meta tags?

### ISSUE THREAD

**Issue by Matty9191** [humboldtux/startbootstrap-clean-blog#31]
I want to thank you for doing an incredible job on this theme! It looks gorgeous and the layouts are really well done!!! Is there a reason the description and author meta tags are set to "" vs. {{ .Description }} and {{ .???.Author }} by default?:

<meta name="description" content="">
<meta name="author" content="">

I'm sure there is a valid reason but I wasn't able to find it in the available documentation.

Thanks again for the awesome theme!
- Ryan

**Comment by humboldtux** [comment]
Not sure if this is an error from my part, or maybe Hugo new syntax available. PR welcome.

**Comment by Matty9191** [comment]
I'll submit a PR later this week once I clean up my solution. Wanted to verify that this wasn't intentional first. Thanks for the response!

**Comment by humboldtux** [comment]
Thanks for #32
