### ISSUE TITLE
Contact form doesn't work

### ISSUE THREAD

**Issue by 11jwolfe2** [humboldtux/startbootstrap-clean-blog#36]
Get the error that the  server is currently down. 

Have edited the email and verified that the post function works in the chrome inspect console. I am having the same issue with the Agency theme as well using formspree.io. I am assuming it is a jquery issue, but I am a little to new to know the answer. I am hosting the site via a git hubrepo, feel free to visit the site at [theinternet.onthewifi.com](theinternet.onthewifi.com), the repo is [here](https://github.com/11jwolfe2/11jwolfe2.github.io)

![image](https://user-images.githubusercontent.com/15834012/36791351-92a0d658-1c65-11e8-9c1f-d8c51072d4c4.png)

![image](https://user-images.githubusercontent.com/15834012/36791204-215cfb20-1c65-11e8-8831-4755948d7c2a.png)

**Comment by humboldtux** [comment]
I have just received email from the form on my test site

![hugo](https://user-images.githubusercontent.com/65201/36791559-7b486db2-1c98-11e8-8099-8649b6da739f.png)

I think your form is broken, not the theme form

**Comment by 11jwolfe2** [comment]
If I updated the email with my sites email address shouldn't this change the form? Why would it still be posting to your email?

**Comment by humboldtux** [comment]
Sorry, i wasn't clear:

The email came from MY test site at www.humboldtux.net/sbcb-demo/contact.
I've just received it from someone who was certainly testing it.

What i mean is that the original form from the theme is working

**Comment by 11jwolfe2** [comment]
I went back and coppied your sbcb-demo to a t but replcaed in the clean-blog.js file the email. I did this buy adding a new static folder and js folder, to not edit the theme as you said in the read me. I however am still getting this message. Any advice?

![image](https://user-images.githubusercontent.com/15834012/36797562-43b04e3c-1c76-11e8-9eb7-3abd62551c31.png)

**Comment by 11jwolfe2** [comment]
I figured out the issue. It was with registering the website with freeform.io. I inserted their test form instead of the theme form and used that to send the initial email used to register the page. Then I changed the form back to the theme form and now the form is working. This is a weird issue with freeform.io, i believe.
