### ISSUE TITLE
Errors on site without expected parameters set

### ISSUE THREAD

**Issue by paskal** [humboldtux/startbootstrap-clean-blog#37]
Hello!

$subj, when trying to run this theme against my [blog](https://github.com/paskal/terrty/tree/master/blog) source I get following:

```
Building sites … ERROR 2018/03/20 18:18:56 Error while rendering "page" in "post/": template: theme/post/single.html:15:20: executing "theme/post/single.html" at <partial "meta.html" ...>: error calling partial: template: theme/partials/meta.html:4:74: executing "theme/partials/meta.html" at <.Site.Params.datefor...>: invalid value; expected string
ERROR 2018/03/20 18:18:56 in .Render: Failed to execute template "theme/post/archive.html": template: theme/post/archive.html:2:105: executing "theme/post/archive.html" at <.Site.Params.datefor...>: invalid value; expected string
ERROR 2018/03/20 18:18:56 in .Render: Failed to execute template "theme/post/summary.html": template: theme/post/summary.html:7:25: executing "theme/post/summary.html" at <partial "meta.html" ...>: error calling partial: template: theme/partials/meta.html:4:74: executing "theme/partials/meta.html" at <.Site.Params.datefor...>: invalid value; expected string
```

The reason is likely some absent `.Site.` parameter but you can't tell it from error message, I guess input parameters handling could be improved.  `.Site.Params.datefor...` in my case is `Jan 2, 2006`.

As a result, main page don't have posts preview and of two posts pages I've checked only one worked, second was not rendered.

**Comment by humboldtux** [comment]
I'm not using this theme anymore.
New maintainer wanted.

**Comment by paskal** [comment]
Something as simple as https://github.com/yursan9/manis-hugo-theme/commit/c11fc5d62aef1c5924ccad98dd0f910d7f6b1f34 will do.
