### ISSUE TITLE
Can't change the capitalized title

### ISSUE THREAD

**Issue by jflehe** [humboldtux/startbootstrap-clean-blog#4]
Hello,
First of all you make a great work, the theme is very clean ...
I'm tryiing to change how the title are displayed, but i'm not used to handle CSS. I prefer that the in the title not every word are capitalized. Could you help me please ? Thanks

**Comment by humboldtux** [comment]
Hi,

The layout templates is using the `title`function to render h1 titles capitalized: https://github.com/humboldtux/startbootstrap-clean-blog/search?utf8=%E2%9C%93&q=%3Ch1%3E%7B%7B+title+.Title+%7D%7D%3C%2Fh1%3E&type=Code

It might not be a good decision as it's not really flexible.

You have two options:
* In your Hugo site, create a `layout` dir with all the previous template defining the h1 element, and remove the title function.
* Wait a little i work on this, and push a commit :smile:

**Comment by jflehe** [comment]
I think the second option will be the best for me ;-)

**Comment by humboldtux** [comment]
Hi @jflehe, i've changed the templates, tell me if it's ok for you.

**Comment by jflehe** [comment]
Hi @humboldtux, it's fine, it work very well.
Thanks.

**Comment by humboldtux** [comment]
De rien :smile:
