### ISSUE TITLE
Inclusion of LESS files

### ISSUE THREAD

**Issue by samozzy** [humboldtux/startbootstrap-clean-blog#7]
The [original bootstrap theme](https://github.com/BlackrockDigital/startbootstrap-clean-blog) has its CSS based on LESS.
While Hugo doesn't come with a compiler, including a pre-compiled and the LESS files makes a lot of sense and makes editing the CSS (tweaking the font across the board, for instance) significantly easier.

**Comment by humboldtux** [comment]
I plan to incorporate less from the original template. I will hopefully tackle this by August if i have time
during my holidays. You are more than welcome to contribute a PR.

**Comment by humboldtux** [comment]
Waiting for original theme to move to BS4 using LESS or SASS.
