### ISSUE TITLE
Separate tags and categories consistently by comma

### ISSUE THREAD

**Issue by jesusgalvan** [humboldtux/startbootstrap-clean-blog#9]
As of now, the theme separates the tags and commas like:
![screen shot 2016-07-23 at 9 18 36 am](https://cloud.githubusercontent.com/assets/2798097/17078939/a94fd1f0-50b6-11e6-96a6-6eed7fe45e78.png)

Would a pull request that changes it to this be considered?:
![screen shot 2016-07-23 at 9 18 20 am](https://cloud.githubusercontent.com/assets/2798097/17078944/bab5e308-50b6-11e6-90c6-c64534599427.png)

**Comment by humboldtux** [comment]
PR more than welcome :+1:

**Comment by humboldtux** [comment]
Thanks.
